version: "2"

services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - /workspace/node-amazon-dynamo/docker/elk/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    links:
      - elasticsearch

  kibana:
    image: evo9192/kibana:eswait
    volumes:
      - /workspace/node-amazon-dynamo/docker/elk/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    links:
      - elasticsearch