filebeat:
    prospectors:
        -
            paths:
                - "/dynamo/logs/file.log"
            document_type: app
output:
    logstash:
        enabled: true
        hosts: ["10.0.2.15:5000"]
        index: logstash