filebeat:
    prospectors:
        -
            paths:
                - "/dynamo/logs/file.log"
            document_type: app
output:
    logstash:
        enabled: true
        hosts: ["192.168.99.10:5000"]
        index: logstash